name: Test
version: 2.3
api: 1.12.0
main: TahaTheHacker\Anvil\Main
author: TahaTheHacker
load: POSTWORLD
permissions:
  anvil:
    description: "Allow use all Anvil commands."
    default: false
    children:
      anvil.feather:
    description: "Allows to use flying feather."
    default: op
