name: Anvil
version: 2.3
api: 1.12.0
main: TahaTheHacker\Anvil\Main
author: TahaTheHacker
load: POSTWORLD
commands:
 joinmatch:
  description: "Runs My First command it tpes to worlds"
  usage: "/joinmatch <world>"
  permission: anvil.taha
  default: true
permissions:
  anvil:
    description: "Allow use all Anvil commands."
    default: false
    children:
      anvil.feather:
    description: "Allows to use flying feather."
    default: op
