---
#HelpModifer's default config
#sets the permission node of displaying the messages:
permission: hp.messages.show
#messages will be shown when doing /help:
messages:
  - "Hello, {player}!"
  - "do /list to see who are the players online!"
  - "and have fun!"
...
